export const APP_NAME = 'Super Clones'
export const APP_LOGO_PATH = '/WEBLOGO-TEXT-BLACK.png'
export const APP_LOGO_PATH_WHITE = '/WEBLOGO-TEXT-WHITE.png'
/** @deprecated Use BrandLogo / APP_LOGO_PATH */
export const APP_LOGO_MARK = 'SC'
export const APP_COPYRIGHT = 'Super Clones © 2026'
export const APP_DEFAULT_AUTHOR = 'Super Clones'
export const APP_DEFAULT_AUTHOR_ICON = 'S'
export const CART_STORAGE_KEY = 'superclones-cart'
export const LEGACY_CART_STORAGE_KEY = 'triplezero-cart'
