/** Product category labels used in filters and the shop sidebar. */
export const SHOP_CATEGORIES = [
  'All',
  'Free',
  'PHP Script',
  'HTML',
  'React',
  'WordPress Plugin',
  'WordPress Theme',
  'Angular',
  'CMS',
  'Wireframe Kits',
  'UI templates',
  'Illustrations',
  'Icon Sets',
  'Mobile App',
  '3D Assets',
  'Bootstrap',
  'Vue.js',
  'Node.js',
  'Laravel',
  'Django',
  'Flutter',
  'Swift',
  'Kotlin',
  'Shopify',
  'Magento',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Game Assets',
  'Audio & Music',
  'Video Templates',
  'Python',
  '.NET',
  'Ruby on Rails',
] as const

export type ShopCategory = (typeof SHOP_CATEGORIES)[number]
