name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: '20'
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /catalogus
          NEXT_PUBLIC_APP_URL: https://superclones.cloud/catalogus
